### ISSUE TITLE
FTP Storage

### ISSUE THREAD

**Issue by Gounlaf** [codeideo/paranoik-backups#3]
Is it possible, for you, to write a FTP Storage ? I don't know if it's simple or not...

Thanks

**Comment by jordanjambazov** [comment]
Hey @Gounlaf,

Have a happy, healthy and successful 2015 year!

The problem is that a Python library called "six" has been added as dependency to provide compatibility between Python 2 and Python 3. I just added that library to `setup.py`. Thank you for reporting the issue.

Here is the commit that fixes it: https://github.com/codeideo/paranoik-backups/commit/fe24766cc6b6980307d8c341a8f84f3b46bff17e

You can fix the issue either running again `python setup.py install`, or by installing `six` manually, by using `pip install six`.

Kind regards,
Jordan

**Comment by Gounlaf** [comment]
Hi @jordanjambazov,

Unfortunally, it's still not working

Here is the complete error

```python
Traceback (most recent call last):
  File "./redmine-backup.py", line 5, in <module>
    from paranoik.backup.providers.mysql import MySQL
  File "/usr/local/lib/python2.7/dist-packages/Paranoik-0.0.7-py2.7.egg/paranoik/backup/providers/mysql.py", line 8, in <module>
    from paranoik.backup.backupable import Backupable
  File "/usr/local/lib/python2.7/dist-packages/Paranoik-0.0.7-py2.7.egg/paranoik/backup/backupable.py", line 6, in <module>
    from six import add_metaclass
ImportError: cannot import name add_metaclass
```

**Comment by jordanjambazov** [comment]
Hey @Gounlaf 

Try to do this:

`pip install --upgrade six`

Also check if you have a file called `six.py` in your project.

**Comment by Gounlaf** [comment]
Now working ;)
Thanks !
